hide_download: true
hide_download_original: null
leftnav:
- identifier: c0f1e6e9-09ac-51f1-5935-a75427b4483e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 3b701404-2733-8781-c299-aee3cf64a26e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 1004086e-b0e0-92b8-5cc7-ee8d35fbedc5
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 30
- identifier: 5b4e66b5-671b-45f0-7c9d-c586304641f9
  name: Labs
  pageRef: /pages/labs
  weight: 40
- identifier: acc673e2-1452-4166-513f-e2f42dcc105b
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 2cfe5eb9-053d-ff75-413f-c153d48d9117
  name: Projects
  pageRef: /pages/projects
  weight: 60
